services:
  github-actions-runner:
    image: evl8/esd-github-actions-runner
    environment:
      - URL=https://github.com/GlennVerstraelenFontys/esd-github-actions-assignment
      - TOKEN=AQ4ZNU53A7MS6JB6THP7663HJWQEC
    networks:
      - esd
  nexus:
    image: sonatype/nexus:oss 
    ports:
    - "8081:8081"
    networks:
      - esd
networks:
  esd:
    driver: bridge